version: "3"

services:
  zookeeper:
    image: "confluentinc/cp-zookeeper:7.0.0"
    container_name: "zookeeper"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000 
      - ZOOKEEPER_SYNC_LIMIT=2
    networks:
      kafka_net:
        ipv4_address: "192.168.12.4"
    ports:
      - "2181:2181"
  kafka:
    image: "confluentinc/cp-kafka:7.0.0"
    depends_on:
      - zookeeper
    container_name: "kafka"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092 
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_BROKER_ID=2 
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 
    ports:
      - "9092:9092"
    networks:
      kafka_net:
        ipv4_address: "192.168.12.5"   
networks:
  kafka_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  192.168.12.0/24